"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""

try:
    import cStringIO.StringIO as BytesIO
except ImportError:
    from io import BytesIO
import struct

import comm.quaternion_t

import comm.vec3d_t

import comm.rot3d_t

class pose3d_t(object):
    __slots__ = ["position", "rotation", "quaternion"]

    __typenames__ = ["comm.vec3d_t", "comm.rot3d_t", "comm.quaternion_t"]

    __dimensions__ = [None, None, None]

    def __init__(self):
        self.position = comm.vec3d_t()
        self.rotation = comm.rot3d_t()
        self.quaternion = comm.quaternion_t()

    def encode(self):
        buf = BytesIO()
        buf.write(pose3d_t._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        assert self.position._get_packed_fingerprint() == comm.vec3d_t._get_packed_fingerprint()
        self.position._encode_one(buf)
        assert self.rotation._get_packed_fingerprint() == comm.rot3d_t._get_packed_fingerprint()
        self.rotation._encode_one(buf)
        assert self.quaternion._get_packed_fingerprint() == comm.quaternion_t._get_packed_fingerprint()
        self.quaternion._encode_one(buf)

    def decode(data):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != pose3d_t._get_packed_fingerprint():
            raise ValueError("Decode error")
        return pose3d_t._decode_one(buf)
    decode = staticmethod(decode)

    def _decode_one(buf):
        self = pose3d_t()
        self.position = comm.vec3d_t._decode_one(buf)
        self.rotation = comm.rot3d_t._decode_one(buf)
        self.quaternion = comm.quaternion_t._decode_one(buf)
        return self
    _decode_one = staticmethod(_decode_one)

    _hash = None
    def _get_hash_recursive(parents):
        if pose3d_t in parents: return 0
        newparents = parents + [pose3d_t]
        tmphash = (0xc1034df7526fae6f+ comm.vec3d_t._get_hash_recursive(newparents)+ comm.rot3d_t._get_hash_recursive(newparents)+ comm.quaternion_t._get_hash_recursive(newparents)) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff) + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _get_hash_recursive = staticmethod(_get_hash_recursive)
    _packed_fingerprint = None

    def _get_packed_fingerprint():
        if pose3d_t._packed_fingerprint is None:
            pose3d_t._packed_fingerprint = struct.pack(">Q", pose3d_t._get_hash_recursive([]))
        return pose3d_t._packed_fingerprint
    _get_packed_fingerprint = staticmethod(_get_packed_fingerprint)

